title: Des légumes et des rêves
author: Hélène
name: AracLovers
email: your-email@domain.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Des légumes et des rêves

theme: minima